[project]
name = "flask-marshmallow"
version = "1.5.0"
description = "Flask + marshmallow for beautiful APIs"
readme = "README.rst"
license = "MIT"
maintainers = [
  { name = "Steven Loria", email = "oss@stevenloria.com" },
  { name = "Stephen Rosen", email = "sirosen0@gmail.com" },
]
classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
requires-python = ">=3.10"
dependencies = ["Flask>=2.2", "marshmallow>=4.0.0"]

[project.urls]
Issues = "https://github.com/marshmallow-code/flask-marshmallow/issues"
Funding = "https://opencollective.com/marshmallow"

[project.optional-dependencies]
sqlalchemy = ["flask-sqlalchemy>=3.0.0", "marshmallow-sqlalchemy>=1.4.0"]

[dependency-groups]
docs = ["marshmallow-sqlalchemy>=0.19.0", "sphinx-issues", "sphinx>=8.1"]
tests = ["pytest"]
dev = [{ include-group = "tests" }, "tox", "tox-uv", "pre-commit>=4.5,<5.0"]

[tool.uv]
default-groups = ["dev"]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.sdist]
include = ["docs/", "tests/", "CHANGELOG.rst", "CONTRIBUTING.rst", "tox.ini"]
exclude = ["docs/_build/"]

[tool.ruff]
src = ["src"]
fix = true
show-fixes = true
output-format = "full"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "B",  # flake8-bugbear
  "E",  # pycodestyle error
  "F",  # pyflakes
  "I",  # isort
  "UP", # pyupgrade
  "W",  # pycodestyle warning
]

[tool.pytest.ini_options]
filterwarnings = [
  "error",
  # TODO: Remove below when Python 3.10 is no longer supported
  "ignore:distutils Version classes are deprecated\\. Use packaging.version instead\\.:DeprecationWarning:marshmallow",
  "ignore:The distutils package is deprecated:DeprecationWarning",
]
