[tox]
envlist=
    lint
    py{310,311,312,313,314}
    py314-marshmallowdev
    py310-lowest
    docs

[testenv]
extras = sqlalchemy
dependency_groups = tests
deps =
    marshmallowdev: https://github.com/marshmallow-code/marshmallow/archive/dev.tar.gz
    lowest: marshmallow==4.0.0
    lowest: marshmallow-sqlalchemy==1.4.0
    lowest: flask-sqlalchemy==3.0.0
    lowest: flask==2.2
    lowest: werkzeug==2.2.2
    ; lowest version supported by marshmallow-sqlalchemy
    lowest: sqlalchemy==1.4.40
commands = pytest {posargs}

[testenv:lint]
deps = pre-commit~=4.5.1
skip_install = true
commands = pre-commit run --all-files

[testenv:docs]
dependency_groups = docs
commands = sphinx-build docs/ docs/_build {posargs}

; Below tasks are for development only (not run in CI)

[testenv:docs-serve]
deps = sphinx-autobuild
dependency_groups = docs
commands = sphinx-autobuild --port=0 --open-browser --delay=2 docs/ docs/_build {posargs} --watch src --watch CONTRIBUTING.rst --watch README.rst

[testenv:readme-serve]
deps = restview
skip_install = true
commands = restview README.rst

